apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: f2a16a4d54b4051d065c9b1f7f70e0724d8a5d78
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: f2a16a4d54b4051d065c9b1f7f70e0724d8a5d78
resources:
  - manifests.yaml