apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io/azure-vote-front
    newTag: e28c0aa106a1dc79d8a5683ca306264a9bf223a3
  - name: mtjacr001/.azurecr.io/azure-vote-back
    newTag: e28c0aa106a1dc79d8a5683ca306264a9bf223a3
resources:
  - manifests.yaml