apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: e00393dc3538d51cb1cd9b778c5ab53680158262
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: e00393dc3538d51cb1cd9b778c5ab53680158262
resources:
  - manifests.yaml