apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: 100
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: 100
resources:
  - manifests.yaml