apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: 277a069a7c213b0588bbbba34fb1bb957161701e
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: 277a069a7c213b0588bbbba34fb1bb957161701e
resources:
  - manifests.yaml