apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: c8573de76ac1330c1d32c41ae7b6a29a5d89472c
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: c8573de76ac1330c1d32c41ae7b6a29a5d89472c
resources:
  - manifests.yaml