apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001.azurecr.io//azure-vote-front
    newTag: 0a3adcfc400a92f9c5cb2c0054906931ea692ae7
  - name: mtjacr001.azurecr.io//azure-vote-back
    newTag: 0a3adcfc400a92f9c5cb2c0054906931ea692ae7
resources:
  - manifests.yaml