apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vws-app
  namespace: vws-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vws-app
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50