apiVersion: v1
kind: Service
metadata:
  name: vws-backend-service
  namespace: vws-app
spec:
  type: ClusterIP
  #externalTrafficPolicy: Local
  ports:
  - port: 3001
    # nodePort: 32302
  selector:
    app: vws-backend